### ISSUE TITLE
[Arguments(decimal, decimal)] does not infer correct type since v0.50.0

### ISSUE THREAD

**Issue by AlexandreBossard** [thomhurst/TUnit#2764]
```csharp
    [Test]
    [Arguments(2_000, 123_999.00000000000000001)]
    [Arguments(2_000.00000000000000001, 123_999)]
    [Arguments(2_000.00000000000000001, 123_999.00000000000000001)]
    public async Task Transfer(decimal debit, decimal credit)
{
        Console.WriteLine("{0} {1}", debit, credit);
}
```
prints
```
2000 123999
2000 123999
2000 123999
```
which is incorrect :-)

And I can confirm the value in the debugger.

I tried casting to decimal and using the `M` suffix literal, but it does not compile.

**Comment by BramMusters** [comment]
I think this is a similar issue:

```
    [Test]
    [Arguments(0.5)]
    [Arguments(0.75)]
    [Arguments(1)]
    public void Test(decimal test)
    {
        return;
    }
```

The second and third tests fail with `Expected exactly 1 argument, but got 2`

**Comment by thomhurst** [comment]
@AlexandreBossard @BramMusters this should be fixed in the latest version

**Comment by AlexandreBossard** [comment]
I'm sorry, but it still does not work. I've updated to `v0.61.39.0` and unskipped the exact same test, still fails.

**Comment by thomhurst** [comment]
Roslyn automatically picks up the constant value as a double, so it might be losing precision there.

Try using a string argument instead - does that work?

**Comment by AlexandreBossard** [comment]
Using strings and keeping the `decimal` arguments, doesn't work, unsurprisingly.  I can use strings all the way down and do a "decimal.Parse()` but that kind of defeat the point. Also it used to work before `0.50.0`.

**Comment by AlexandreBossard** [comment]
Thanks for the fix, but we found a "huge" regression when upgrading to 0.64.0 and above.
This snippet fails to compile:

```csharp

public class ServiceTests
{
    private const int BatchSize = 42;

    [Test]
    [Arguments(BatchSize)]
    public async Task TestMethod(decimal batchingSize)
    {
       // Test code
    }
}
```
```
error CS0103: The name 'BatchSizem' does not exist in the current context   # <- note the extra "m"
error CS0103: The name 'BatchSize' does not exist in the current context
```
The code generation fails to recognize this is a named constant a suffixes it with the decimal literal.
