### ISSUE TITLE
[Bug]: FlowSuppressingHostedService does not forward IDisposable / IAsyncDisposable to inner service

### ISSUE THREAD

**Issue by JohnVerheij** [thomhurst/TUnit#5651]
### Description

TUnit.AspNetCore.TestWebApplicationFactory<T> wraps every registered IHostedService in a FlowSuppressingHostedService to run StartAsync on a clean ExecutionContext. The wrapper implements IHostedLifecycleService and forwards its methods, but it does not implement IDisposable or IAsyncDisposable. When the DI container disposes the host, it only sees the non-disposable wrapper, so the inner service's Dispose / DisposeAsync is never called.

For hosted services that own unmanaged resources (gRPC channels, database connections, process handles, file streams), this is a silent resource leak.

Introduced in commit 76c4d4ed0 / PR #5589 / #5598 (merged 2026-04-17) which added FlowSuppressingHostedService to solve a span-correlation issue during StartAsync. The disposal forwarding was not part of that change.

The sibling class TracedWebApplicationFactory in the same package already implements the correct dual-interface forwarding pattern, so this is a gap, not a novel design question.

### Expected Behavior

When the DI container disposes the host (via either sync Dispose or async DisposeAsync on the WebApplicationFactory), the inner IHostedService's Dispose / DisposeAsync should be called so any owned resources are released.

### Actual Behavior

The wrapper does not implement IDisposable or IAsyncDisposable, so the DI container skips it when iterating disposables. The inner service's Dispose / DisposeAsync is never called. Resources leak silently.

### Steps to Reproduce

Construct the wrapper directly and check whether disposal is forwarded. This repro does not require a WebApplicationFactory or a host:

```csharp
using Microsoft.Extensions.Hosting;
using TUnit.AspNetCore;

public class DisposalRepro
{
    [Test]
    public async Task Inner_DisposeAsync_Is_Called_By_Wrapper()
    {
        var inner = new AsyncProbe();
        var wrapper = new FlowSuppressingHostedService(inner);

        await ((IAsyncDisposable)wrapper).DisposeAsync();

        await Assert.That(inner.DisposeAsyncCalled).IsTrue();
        // FAILS on 1.37.10: cast to IAsyncDisposable is invalid at runtime
        // because the wrapper does not declare the interface.
    }
}

internal sealed class AsyncProbe : IHostedService, IAsyncDisposable
{
    public bool DisposeAsyncCalled { get; private set; }
    public Task StartAsync(CancellationToken ct) => Task.CompletedTask;
    public Task StopAsync(CancellationToken ct) => Task.CompletedTask;
    public ValueTask DisposeAsync() { DisposeAsyncCalled = true; return ValueTask.CompletedTask; }
}

### TUnit Version

1.37.10

### .NET Version

.NET 10.0 (also affects net8.0 and net9.0 targets)

### Operating System

Other (please specify in additional context)

### IDE / Test Runner

dotnet CLI (dotnet test / dotnet run)

### Error Output / Stack Trace

```shell

```

### Additional Context

- AOT / trimming: not AOT-specific. Reproduces identically under JIT and Native AOT publish.
- Custom configuration: none. Standard TestWebApplicationFactory usage with the default SuppressHostedServiceExecutionContextFlow = true.
- Specific test data: none. Reproduces with any IHostedService that implements IDisposable or IAsyncDisposable.
- Target framework coverage: affects all published TFMs of TUnit.AspNetCore.Core (net8.0, net9.0, net10.0).
- Workaround: override SuppressHostedServiceExecutionContextFlow => false on the factory subclass. Restores disposal but disables flow suppression (trading one desirable behaviour for another).
- Have a patch with regression tests on a local branch; PR to follow.

### IDE-Specific Issue?

- [x] I've confirmed this issue occurs when running via `dotnet test` or `dotnet run`, not just in my IDE

**Comment by JohnVerheij** [comment]
PR open at #5652 for review. Regression tests included (7 pure-unit-tests, 10 consecutive runs clean on net8/9/10).
