### ISSUE TITLE
[Bug]: Missing Method `HasLength` after update

### ISSUE THREAD

**Issue by samtrion** [thomhurst/TUnit#5401]
### Description

After the Update to 1.27.0 I have the CI Error

```txt
error CS1061: 'ValueAssertion<string>' does not contain a definition for 'HasLength' and no accessible extension method 'HasLength' accepting a first argument of type 'ValueAssertion<string>' could be found (are you missing a using directive or an assembly reference?) [D:\a\arguments\arguments\tests\NetEvolve.Arguments.Tests.Unit\NetEvolve.Arguments.Tests.Unit.csproj::TargetFramework=net8.0]
```

https://github.com/dailydevops/arguments/pull/636

### Expected Behavior

Working Tests, similar to 1.25.0

### Actual Behavior

Errors

### Steps to Reproduce

https://github.com/dailydevops/arguments/pull/636

### TUnit Version

1.27.0

### .NET Version

.NET8, 9, 10

### Operating System

Windows

### IDE / Test Runner

dotnet CLI (dotnet test / dotnet run)

### Error Output / Stack Trace

```shell

```

### IDE-Specific Issue?

- [x] I've confirmed this issue occurs when running via `dotnet test` or `dotnet run`, not just in my IDE

**Comment by thomhurst** [comment]
Yeah this was marked as obsolete a lil while back and I cleared them up in the last version. Alternative now is `.Length(...)`

**Comment by samtrion** [comment]
> Yeah this was marked as obsolete a lil while back and I cleared them up in the last version. Alternative now is `.Length(...)`

Sorry, missed that obsolete warning. :(
