### ISSUE TITLE
Various collection assertions not available when targeting net8.0

### ISSUE THREAD

**Issue by Randactyl** [thomhurst/TUnit#3913]
Collection assertion methods are not available when the test project is targeting .NET 8.0, causing compilation errors. The same code compiles successfully when targeting .NET 9.0 or .NET 10.0. Copilot thinks this appears to be a framework-specific extension method resolution issue.

Expected Behavior:

Collection assertions should work consistently across all supported TUnit TFMs. The following code should compile and run on .NET 8.0:

```csharp
[Test]
public async Task CollectionAssertionsBrokenForListsWhenTargetingNet8_0()
{
    var enumerable = Enumerable.Range(1, 5);
    var list = enumerable.ToList();

    await Assert.That(enumerable).IsNotEmpty();
    await Assert.That(list).IsNotEmpty();

    await Assert.That(enumerable).IsEmpty();
    await Assert.That(list).IsEmpty();

    await Assert.That(enumerable).HasCount(5);
    await Assert.That(list).HasCount(5);

    await Assert.That(enumerable).HasSingleItem();
    await Assert.That(list).HasSingleItem();
}
```

Actual Behavior:

When targeting .NET 8.0, the collection assertion methods produce various errors for Lists and the code fails to compile:

```
error CS1929: 'ValueAssertion<List<int>>' does not contain a definition for 'IsNotEmpty' and the best extension method overload 'StringIsNotEmptyAssertionExtensions.IsNotEmpty(IAssertionSource<string>)' requires a receiver of type 'TUnit.Assertions.Core.IAssertionSource<string>'

error CS1929: 'ValueAssertion<List<int>>' does not contain a definition for 'IsEmpty' and the best extension method overload 'StringIsEmptyAssertionExtensions.IsEmpty(IAssertionSource<string>)' requires a receiver of type 'TUnit.Assertions.Core.IAssertionSource<string>'

error CS1061: 'ValueAssertion<List<int>>' does not contain a definition for 'HasCount' and no accessible extension method 'HasCount' accepting a first argument of type 'ValueAssertion<List<int>>' could be found (are you missing a using directive or an assembly reference?)

error CS0411: The type arguments for method 'HasSingleItemAssertionExtensions.HasSingleItem<TCollection, TItem>(IAssertionSource<TCollection>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
```

The `HasSingleItem()` case is a bit different. I can get it to compile in net8.0 if I provide the type arguments that are otherwise successfully inferred when targeting net9.0 or net10.0.

Reproduction:

1. Create a test project targeting .NET 8.0
2. Add TUnit 1.2.11 package reference
3. Create the test code above
4. Run dotnet build
5. Observe compilation errors

Verification:

✅ NET 9.0: Compiles successfully
✅ NET 10.0: Compiles successfully
❌ NET 8.0: Fails with the errors above

P.S. thank you for your time working on TUnit. I have very much enjoyed using it :)

**Comment by thomhurst** [comment]
Yeah this is because .net 8 doesn't support overload resolution priority. The workaround is to manually cast your object to an `IEnumerable<T>`, or just upgrade :)
