### ISSUE TITLE
Generic data types with implicit tuple operators don't compile in 0.52.25

### ISSUE THREAD

**Issue by Brokolis** [thomhurst/TUnit#2798]
I just updated to 0.52.25 and my project no longer compiles. I'm getting these type of compile errors:

```
0>AotConverters.g.cs(17,22): Error CS1061 : 'object' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
0>AotConverters.g.cs(17,22): Error CS8129 : No suitable 'Deconstruct' instance or extension method was found for type 'object', with 2 out parameters and a void return type.
```

The generated code in the `AotConverters.g.cs` file looks like this (the error happens on the `if (value is (int Value1, int Value2) typedValue)`):
```csharp
internal sealed class AotConverter_0 : IAotConverter
{
    public Type SourceType => typeof((int Value1, int Value2));
    public Type TargetType => typeof(global::TUnitBugs.Foo);
    public object? Convert(object? value)
    {
        if (value == null) return null;
        if (value is (int Value1, int Value2) typedValue)
        {
            return (global::TUnitBugs.Foo)typedValue;
        }
        return value; // Return original value if type doesn't match
    }
}
```

It happens, because pattern `(Foo, Bar)` does NOT match a tuple, but rather a `Deconstruct` method (it's called a [positional pattern](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#positional-pattern)). A proper way to pattern match `object` with a tuple is to use the `ValueTuple` type directly:

```csharp
if (value is ValueTuple<int, int> typedValue)
```

Here's minimal example that reproduces this bug.

```csharp
public record Foo
{
    public static implicit operator Foo((int Value1, int Value2) tuple) => new();
}

public class Tests
{
    [Test]
    [MethodDataSource(nameof(Data))]
    public void Test1(Foo data)
    {
    }

    public static IEnumerable<Foo> Data() => [new()];
}
```

**Comment by thomhurst** [comment]
Hopefully this works in the latest version now!

**Comment by Brokolis** [comment]
Unfortunately, I'm still getting the exact same error in version `0.53.0`. Here's a repository with the minimal repro: https://github.com/Brokolis/TUnitBugs.

**Comment by thomhurst** [comment]
Weird because I've put your exact repro code into the TUnit test project, and it's compiling fine 🤔

https://github.com/thomhurst/TUnit/blob/main/TUnit.TestProject/Bugs/2798/Tests.cs

Have you cleaned and restarted any IDEs to make sure the old source generator isn't cached?

**Comment by Brokolis** [comment]
I just tried to clear my whole `.nuget` directory, deleted `bin` and `obj` directories, ran `dotnet clean && dotnet build` and the problem still persists.

**Comment by thomhurst** [comment]
What Sdk version do you have? And what target platform are you using?

**Comment by Brokolis** [comment]
I'm running Windows 11. `dotnet --list-sdks`:
```shell
8.0.412 [C:\Program Files\dotnet\sdk]
9.0.205 [C:\Program Files\dotnet\sdk]
9.0.302 [C:\Program Files\dotnet\sdk]
9.0.303 [C:\Program Files\dotnet\sdk]
```

Also, I just tried on a fresh Linux machine, my test project builds and runs without any issues. If this is a caching issue on my Windows machine, do you have any tips on where that cache might be stored/how it can be cleared?

**Comment by Brokolis** [comment]
I managed to recreate it in Docker on Linux. It seems like it doesn't work with .NET SDK 9.0.300+, but it is working with 9.0.203 and lower.

```shell
$ docker run -it --rm -v "$(pwd):/src" -w "/src" mcr.microsoft.com/dotnet/sdk:9.0.203 dotnet test
Restore complete (4.2s)
  TUnitBugs succeeded with 1 warning(s) (3.0s) → TUnitBugs/bin/Debug/net9.0/TUnitBugs.dll
    /src/TUnitBugs/Tests.cs(14,36): warning TUnit0046: Return a `Func<T>` rather than a `<T>`.
  TUnitBugs test succeeded (0.4s)

Test summary: total: 1, failed: 0, succeeded: 1, skipped: 0, duration: 0.4s
Build succeeded with 1 warning(s) in 7.9s
$ docker run -it --rm -v "$(pwd):/src" -w "/src" mcr.microsoft.com/dotnet/sdk:9.0.300 dotnet test
Restore complete (9.8s)
  TUnitBugs failed with 2 error(s) and 1 warning(s) (2.7s)
    /src/TUnitBugs/obj/Debug/net9.0/generated/TUnit.Core.SourceGenerator/TUnit.Core.SourceGenerator.Generators.AotConverterGenerator/AotConverters.g.cs(17,22): error CS1061: 'object' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
    /src/TUnitBugs/obj/Debug/net9.0/generated/TUnit.Core.SourceGenerator/TUnit.Core.SourceGenerator.Generators.AotConverterGenerator/AotConverters.g.cs(17,22): error CS8129: No suitable 'Deconstruct' instance or extension method was found for type 'object', with 2 out parameters and a void return type.
    /src/TUnitBugs/Tests.cs(14,36): warning TUnit0046: Return a `Func<T>` rather than a `<T>`.

Build failed with 2 error(s) and 1 warning(s) in 12.8s
```

**Comment by thomhurst** [comment]
Weird!? A dotnet Sdk bug maybe???

**Comment by Brokolis** [comment]
I dug a bit deeper and I believe I found the issue and a possible solution (this is currently just my theory, I haven't exactly tested it yet). TLDR:

`Directory.Build.targets`:
```xml
<Project>
  <PropertyGroup>
    <DefineConstants Condition="$(RoslynVersion) >= 4.7">$(DefineConstants);ROSLYN4_7_OR_GREATER</DefineConstants>
    <DefineConstants Condition="$(RoslynVersion) >= 4.14">$(DefineConstants);ROSLYN4_7_OR_GREATER;ROSLYN4_14_OR_GREATER</DefineConstants>
  </PropertyGroup>
</Project>
```

**Reasoning:** I believe `>=` is doing a string comparison here instead of a numeric one. So when it checks `4.14 >= 4.7`, it actually returns `false`.

Also I managed to recreate the problem in TUnit repository by forcing the 4.14 Roslyn version when running the tests:

```shell
$ cd TUnit.TestProject
$ dotnet build -p:RoslynVersion=4.14 -f net9.0 && dotnet run --no-build -f net9.0 -- --treenode-filter "*/TUnit.TestProject.Bugs._2798/*/*"
```

---

# How I came to this conclusion

1. I opened my test project in Rider with SDK `9.0.304` and navigated to the referenced `TUnit.Core.SourceGenerator` assembly.
2. I then navigated to the exact file that was being referenced and was pointed to this file: `.nuget\packages\tunit.core\0.53.0\analyzers\dotnet\roslyn4.14\cs\TUnit.Core.SourceGenerator.dll`.
3. Then I used Rider's decompiler to confirm, that the new flag in `TUnit.Core.SourceGenerator.DisplayFormats` ***was not*** being set in `roslyn4.14`.
4. I then changed my SDK to `9.0.203` and navigated to the referenced `TUnit.Core.SourceGenerator` assembly.
5. I then navigated to the exact file that was being referenced and was pointed to this file: `.nuget\packages\tunit.core\0.53.0\analyzers\dotnet\roslyn4.7\cs\TUnit.Core.SourceGenerator.dll`.
6. Then I used Rider's decompiler to confirm, that the new flag in `TUnit.Core.SourceGenerator.DisplayFormats` ***was*** being set in `roslyn4.7`.
7. This is where I started to suspect that `ROSLYN4_7_OR_GREATER` was not being set correctly.
8. I cloned TUnit locally and opened `TUnit.Core.SourceGenerator/DisplayFormats.cs`.
9. I then noticed that Rider allows me to select which version of `TUnit.Core.SourceGenerator` to use.
10. After I switched it to `TUnit.Core.SourceGenerator.Roslyn414`, the new flag was immediately grayed out:   <img width="1151" height="534" alt="Image" src="https://github.com/user-attachments/assets/9320b974-87c7-4327-a057-eb893d1271e4" />
11. I then changed the define in `Directory.Build.targets` to `<DefineConstants Condition="$(RoslynVersion) >= 4.14">$(DefineConstants);ROSLYN4_7_OR_GREATER;ROSLYN4_14_OR_GREATER</DefineConstants>` and saw the flag being used with Roslyn414:  <img width="1144" height="535" alt="Image" src="https://github.com/user-attachments/assets/addce21c-02c5-4d4f-8b29-f4855d619c01" />

After this I can only conclude, that since SDK `9.0.300`, the Roslyn version has been updated. And since `ROSLYN4_7_OR_GREATER` seems to be set incorrectly, it never gets activated for Roslyn 4.14+.

I hope my findings will help fix this issue and other similar issues.

**Comment by thomhurst** [comment]
Ooh that's a really good insight!

**Comment by thomhurst** [comment]
I'm reading that they should be parsed as numebrs though

> MSBuild's comparison operators (>=, >, <, <=) automatically attempt to parse both operands as numbers. When both
  operands can be successfully parsed as numbers (integers or decimals), MSBuild performs numeric comparison. Only
  if parsing fails does it fall back to string comparison.

  Since both "4.14" and "4.7" are valid decimal numbers, MSBuild will:
  1. Parse "4.14" as the decimal 4.14
  2. Parse "4.7" as the decimal 4.7
  3. Compare them numerically: 4.14 >= 4.7 = true

**Comment by Brokolis** [comment]
Here's an example `.csproj` (thanks LLMs for generating these :D):

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="0.53.0" />
    </ItemGroup>

    <PropertyGroup>
        <!-- Define some RoslynVersion values for testing -->
        <TestRoslynVersion_Case1>4.6</TestRoslynVersion_Case1>
        <TestRoslynVersion_Case2>4.7</TestRoslynVersion_Case2>
        <TestRoslynVersion_Case3>4.13</TestRoslynVersion_Case3>
        <TestRoslynVersion_Case4>4.14</TestRoslynVersion_Case4>
        <TestRoslynVersion_Case5>5.0</TestRoslynVersion_Case5>
    </PropertyGroup>

    <Target Name="TestRoslynVersionComparison" BeforeTargets="Build">
        <Message Text="--- Testing Roslyn Version Comparisons ---" Importance="high" />

        <!-- Test Case 1: RoslynVersion = 4.6 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case1)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.7">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.14">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 1: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.7? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.14? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 2: RoslynVersion = 4.7 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case2)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.7">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.14">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 2: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.7? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.14? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 3: RoslynVersion = 4.13 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case3)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.7">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.14">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 3: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.7? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.14? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 4: RoslynVersion = 4.14 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case4)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.7">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.14">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 4: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.7? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.14? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 5: RoslynVersion = 5.0 (shows that '5.0' is also treated numerically) -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case5)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.7">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$(RoslynVersionToTest) >= 4.14">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 5: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.7? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  $(RoslynVersionToTest) >= 4.14? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

    </Target>

</Project>
```

And its build output:

```shell
--- Testing Roslyn Version Comparisons ---
Test Case 1: RoslynVersion = 4.6
  4.6 >= 4.7? Result: false
  4.6 >= 4.14? Result: true
Test Case 2: RoslynVersion = 4.7
  4.7 >= 4.7? Result: true
  4.7 >= 4.14? Result: true
Test Case 3: RoslynVersion = 4.13
  4.13 >= 4.7? Result: false
  4.13 >= 4.14? Result: false
Test Case 4: RoslynVersion = 4.14
  4.14 >= 4.7? Result: false
  4.14 >= 4.14? Result: true
Test Case 5: RoslynVersion = 5.0
  5.0 >= 4.7? Result: true
  5.0 >= 4.14? Result: true
```

**Comment by Brokolis** [comment]
If the parsing is using the computer's local culture, that culture might use different decimal point (`.` vs `,`) and thus the parsing might fail. That would be my speculation.

**Comment by thomhurst** [comment]
Interesting! What culture are you using?

**Comment by Brokolis** [comment]
`Console.WriteLine(CultureInfo.CurrentCulture);` returns `en-US` for me.

**Comment by Brokolis** [comment]
[Microsoft warns not to compare versions with comparison operators](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2022#comparing-versions), but instead they suggest to use [built in version comparison functions](https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-version-comparison-functions).

I updated my `.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="0.53.0" />
    </ItemGroup>

    <PropertyGroup>
        <!-- Define some RoslynVersion values for testing -->
        <TestRoslynVersion_Case1>4.6</TestRoslynVersion_Case1>
        <TestRoslynVersion_Case2>4.7</TestRoslynVersion_Case2>
        <TestRoslynVersion_Case3>4.13</TestRoslynVersion_Case3>
        <TestRoslynVersion_Case4>4.14</TestRoslynVersion_Case4>
        <TestRoslynVersion_Case5>5.0</TestRoslynVersion_Case5>
    </PropertyGroup>

    <Target Name="TestRoslynVersionComparison" BeforeTargets="Build">
        <Message Text="--- Testing Roslyn Version Comparisons ---" Importance="high" />

        <!-- Test Case 1: RoslynVersion = 4.6 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case1)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7))">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14))">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 1: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7)? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14)? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 2: RoslynVersion = 4.7 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case2)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7))">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14))">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 2: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7)? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14)? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 3: RoslynVersion = 4.13 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case3)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7))">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14))">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 3: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7)? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14)? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 4: RoslynVersion = 4.14 -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case4)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7))">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14))">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 4: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7)? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14)? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

        <!-- Test Case 5: RoslynVersion = 5.0 (shows that '5.0' is also treated numerically) -->
        <PropertyGroup>
            <RoslynVersionToTest>$(TestRoslynVersion_Case5)</RoslynVersionToTest>
            <ConditionResult_4_7>false</ConditionResult_4_7>
            <ConditionResult_4_14>false</ConditionResult_4_14>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7))">
            <ConditionResult_4_7>true</ConditionResult_4_7>
        </PropertyGroup>
        <PropertyGroup Condition="$([MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14))">
            <ConditionResult_4_14>true</ConditionResult_4_14>
        </PropertyGroup>
        <Message Text="Test Case 5: RoslynVersion = $(RoslynVersionToTest)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.7)? Result: $(ConditionResult_4_7)" Importance="high" />
        <Message Text="  [MSBuild]::VersionGreaterThanOrEquals($(RoslynVersionToTest), 4.14)? Result: $(ConditionResult_4_14)" Importance="high" />
        <Message Text="" Importance="high" />

    </Target>

</Project>
```

And it seems to be behaving as expected:

```shell
--- Testing Roslyn Version Comparisons ---
Test Case 1: RoslynVersion = 4.6
  [MSBuild]::VersionGreaterThanOrEquals(4.6, 4.7)? Result: false
  [MSBuild]::VersionGreaterThanOrEquals(4.6, 4.14)? Result: false
Test Case 2: RoslynVersion = 4.7
  [MSBuild]::VersionGreaterThanOrEquals(4.7, 4.7)? Result: true
  [MSBuild]::VersionGreaterThanOrEquals(4.7, 4.14)? Result: false
Test Case 3: RoslynVersion = 4.13
  [MSBuild]::VersionGreaterThanOrEquals(4.13, 4.7)? Result: true
  [MSBuild]::VersionGreaterThanOrEquals(4.13, 4.14)? Result: false
Test Case 4: RoslynVersion = 4.14
  [MSBuild]::VersionGreaterThanOrEquals(4.14, 4.7)? Result: true
  [MSBuild]::VersionGreaterThanOrEquals(4.14, 4.14)? Result: true
Test Case 5: RoslynVersion = 5.0
  [MSBuild]::VersionGreaterThanOrEquals(5.0, 4.7)? Result: true
  [MSBuild]::VersionGreaterThanOrEquals(5.0, 4.14)? Result: true
```
