### PR TITLE
feat: add support for special floating-point values (NaN, Infinity)

### LINKED ISSUE #3157: New compiler error CS1056: Unexpected character '∞'
The generated code no longer compiles after updating to v0.60.15.
It used to work in v0.60.1.

The errors are like `error CS1056: Unexpected character '∞'`.

This is the generated code:

```cs
DataSources = new global::TUnit.Core.IDataSourceAttribute[]
{
    new global::TUnit.Core.ArgumentsAttribute("1.0", 1f),
    new global::TUnit.Core.ArgumentsAttribute("1.0i32", 1f),
    new global::TUnit.Core.ArgumentsAttribute("0.682287216i32", 0.6822872f),
    new global::TUnit.Core.ArgumentsAttribute("0xFFC00000i32", NaNf),
    new global::TUnit.Core.ArgumentsAttribute("inf32", ∞f),
    new global::TUnit.Core.ArgumentsAttribute("inf", ∞f),
    new global::TUnit.Core.ArgumentsAttribute("-inf32", -∞f),
    new global::TUnit.Core.ArgumentsAttribute("-inf", -∞f),
},
```

These are the attributes:

```cs
[Arguments("1.0", 1d)]
[Arguments("1.0i64", 1d)]
[Arguments("0.682287216i64", 0.682287216d)]
[Arguments("0xFFF8000000000000", double.NaN)]
[Arguments("0xFFF8000000000000i64", double.NaN)]
[Arguments("inf64", double.PositiveInfinity)]
[Arguments("inf", double.PositiveInfinity)]
[Arguments("-inf64", double.NegativeInfinity)]
[Arguments("-inf", double.NegativeInfinity)]
```

### PR DESCRIPTION
**Pull request by thomhurst**
Fixes #3157

### CODE REVIEW

**Comment by slang25** [comment]
You _should_ be able to use `ToCSharpString()` on `TypedConstant` which should give you a valid C# representation of the value, however it's good that you didn't because it's doesn't work for this scenario 😅

I'm just thinking long term it might make more sense to get these things fixed in Roslyn, then it future proofs things and makes the TUnit code simpler.

I'll raise an issue over at dotnet/roslyn for this one (regardless of if it ends up useful here).
