### PR TITLE
fix(assert): adjust overload resolution priorities for dictionary and set assertions

### LINKED ISSUE #4406: [Bug]: Compilation error on set types that implement both IReadonlySet and ISet
### Description

I cannot write assertions directly on `System.Collections.Immutable.ImmutableHashSet<T>`, which implements both `IReadonlySet<T>` and `ISet<T>`. Workaround is to cast it as one of those types first.

This was working in version 1.7.20.

### Expected Behavior

I expected the code to compile.

### Actual Behavior

It gives this error:
```
The call is ambiguous between the following methods or properties: 'TUnit.Assertions.Assert.That<TItem>(System.Collections.Generic.IReadOnlySet<TItem>?, string?)' and 'TUnit.Assertions.Assert.That<TItem>(System.Collections.Generic.ISet<TItem>?, string?)'
```

### Steps to Reproduce

Minimal reproduction code:

```csharp
[Test]
public async Task Set_is_empty()
{
    var set = ImmutableHashSet<int>.Empty;
    await Assert.That(set).IsEmpty();
}
```

### TUnit Version

1.11.8

### .NET Version

.NET 10

### Operating System

Windows

### IDE / Test Runner

dotnet CLI (dotnet test / dotnet run)

### Error Output / Stack Trace

```shell

```

### Additional Context

_No response_

### IDE-Specific Issue?

- [x] I've confirmed this issue occurs when running via `dotnet test` or `dotnet run`, not just in my IDE

### PR DESCRIPTION
**Pull request by thomhurst**
Fixes #4406

### CODE REVIEW

**Comment by thomhurst** [comment]
## Summary
This PR fixes ambiguous overload resolution for types implementing both mutable and read-only collection interfaces (e.g., ImmutableHashSet<T>) by adjusting overload resolution priorities.

## Critical Issues
None found ✅

## Suggestions
None - the fix is minimal, targeted, and includes a proper regression test.

## Analysis
The PR resolves the compilation error reported in #4406 by adjusting `OverloadResolutionPriority` attributes to break ambiguity:

**For Sets:**
- `ISet<T>`: priority 2 → 3
- `IReadOnlySet<T>`: stays at priority 2

**For Dictionaries (preventive fix):**
- `IDictionary<TKey, TValue>`: priority 2 → 3
- `IReadOnlyDictionary<TKey, TValue>`: priority 3 → 2

This makes mutable interfaces (priority 3) preferred over read-only interfaces (priority 2) when types implement both, which is consistent and reasonable since mutable interfaces are more specific.

Both `SetAssertion<T>` and `ReadOnlySetAssertion<T>` provide identical functionality through their adapters, so choosing either interface produces the same assertion behavior. The test case properly validates the fix using the exact reproduction from the issue.

## Verdict
✅ **APPROVE** - No critical issues

**Comment by thomhurst** [comment]
## Summary
Fixes compilation error for types implementing both IReadOnlySet and ISet (like ImmutableHashSet) by adjusting overload resolution priorities.

## Critical Issues
None found ✅

## Analysis
The PR correctly addresses issue #4406 by adjusting OverloadResolutionPriority attributes:

- **ISet<T>**: Priority 2 → 3 (now preferred over IReadOnlySet<T>)
- **IDictionary**: Priority 2 → 3 (now preferred over IReadOnlyDictionary)
- **IReadOnlyDictionary**: Priority 3 → 2

This ensures that when a type implements both interfaces (like ImmutableHashSet<T> or ImmutableDictionary<K,V>), the more specific mutable interface overload is chosen, resolving the ambiguity.

The changes follow TUnit rules:
- ✅ PublicAPI snapshots updated correctly (.verified.txt files)
- ✅ Test case added to verify the fix
- ✅ No performance concerns (not a hot path)

## Verdict
✅ **APPROVE** - No critical issues
