### ISSUE TITLE
[Bug]: Removal of obsolete members is a breaking change and should cause a semver-major version bump

### ISSUE THREAD

**Issue by davidmehren** [thomhurst/TUnit#5539]
### Description

Various functions like `HasCount` were removed in https://github.com/thomhurst/TUnit/commit/df31e910e144cd8d91a5218ace0b4f06d7438419

### Expected Behavior

Breaking changes cause a semver-major version bump.

### Actual Behavior

The change was introduced in a minor release, [v1.27.0](https://github.com/thomhurst/TUnit/releases/tag/v1.27.0)

### Steps to Reproduce

1. Have tests that compile with version < 1.27
2. Upgrade
3. Observe compilation errors

### TUnit Version

1.33.0

### .NET Version

NET 10

### Operating System

Linux

### IDE / Test Runner

dotnet CLI (dotnet test / dotnet run)

### Error Output / Stack Trace

```shell

```

### IDE-Specific Issue?

- [ ] I've confirmed this issue occurs when running via `dotnet test` or `dotnet run`, not just in my IDE
