### ISSUE TITLE
Compile error when test argument is nullable

### ISSUE THREAD

**Issue by robertcoltheart** [thomhurst/TUnit#3170]
The following test fails to compile:

```c#
public class Class1
{
    [Test]
    [Arguments(1, 1)]
    [Arguments(1, null)]
    public async Task TestCase(decimal v1, decimal? v2)
    {
        await Assert.That(v1).IsEqualTo(v2.GetValueOrDefault());
    }
}
```

Compile error is:

```
Class1_TestCase_f103a4933a624f96920902ad73ebaaa7.g.cs(37,63,37,65): error CS0103: The name 'nm' does not exist in the current context
```

This is a regression, since this test works fine in `0.59.0`
