### ISSUE TITLE
Package upgrade: .Ambiguous Member reference on

### ISSUE THREAD

**Issue by Josehardrock** [thomhurst/TUnit#3930]
After upgrading from package version 0.73 TUnit to 1.2.*, Member Assertions are causing ambiguous reference.

` error CS0121: The call is ambiguous between the following methods or properties: 'AssertionExtensions.Member<TObject, TMember, TTransformed>(IAssertionSource<TObject>, Expression<Func<TObject, TMember>>, Func<IAssertionSource<TMember>, Assertion<TTransformed>>)' and 'AssertionExtensions.Member<TObject, TMember>(IAssertionSource<TObject>, Expression<Func<TObject, TMember>>, Func<IAssertionSource<TMember>, Assertion<TMember>>)'`

**Comment by thomhurst** [comment]
Can you post some of the problematic code?

**Comment by Josehardrock** [comment]
Same code, works with version 0.73
<img width="485" height="310" alt="Image" src="https://github.com/user-attachments/assets/04479b64-7090-4236-b12f-8a68fb61bfbd" /> 

After update to 1.2.11

<img width="1337" height="453" alt="Image" src="https://github.com/user-attachments/assets/6794b97f-0880-4d47-834f-f631cf489edf" />

**Comment by Josehardrock** [comment]
Issue still appearing with latest version. 

<img width="1202" height="141" alt="Image" src="https://github.com/user-attachments/assets/77d5710b-08aa-476a-b3bf-a718bc4231dc" />

**Comment by thomhurst** [comment]
Are you on .NET 8 or older?

**Comment by Josehardrock** [comment]
I'm using dotnet 10. It might be nice to add a Member assertion to the templates

**Comment by Josehardrock** [comment]
I'm using .Net 10, the problem seems to be related to <LangVersion>12.0</LangVersion>. Using either 10 or 14 makes it work, but using Lang 12, raises the same problem.

**Comment by thomhurst** [comment]
TUnit uses overload resolution priority attributes which work from Lang version 14 I believe. So just keep the version high 😄
