### ISSUE TITLE
New compiler error CS1056: Unexpected character '∞'

### ISSUE THREAD

**Issue by PhilippNaused** [thomhurst/TUnit#3157]
The generated code no longer compiles after updating to v0.60.15.
It used to work in v0.60.1.

The errors are like `error CS1056: Unexpected character '∞'`.

This is the generated code:

```cs
DataSources = new global::TUnit.Core.IDataSourceAttribute[]
{
    new global::TUnit.Core.ArgumentsAttribute("1.0", 1f),
    new global::TUnit.Core.ArgumentsAttribute("1.0i32", 1f),
    new global::TUnit.Core.ArgumentsAttribute("0.682287216i32", 0.6822872f),
    new global::TUnit.Core.ArgumentsAttribute("0xFFC00000i32", NaNf),
    new global::TUnit.Core.ArgumentsAttribute("inf32", ∞f),
    new global::TUnit.Core.ArgumentsAttribute("inf", ∞f),
    new global::TUnit.Core.ArgumentsAttribute("-inf32", -∞f),
    new global::TUnit.Core.ArgumentsAttribute("-inf", -∞f),
},
```

These are the attributes:

```cs
[Arguments("1.0", 1d)]
[Arguments("1.0i64", 1d)]
[Arguments("0.682287216i64", 0.682287216d)]
[Arguments("0xFFF8000000000000", double.NaN)]
[Arguments("0xFFF8000000000000i64", double.NaN)]
[Arguments("inf64", double.PositiveInfinity)]
[Arguments("inf", double.PositiveInfinity)]
[Arguments("-inf64", double.NegativeInfinity)]
[Arguments("-inf", double.NegativeInfinity)]
```

**Comment by PhilippNaused** [comment]
The bug is also in v0.60.15.
