### PR TITLE
fix: restore [Obsolete] members removed in v1.27 (#5539)

### LINKED ISSUE #5539: [Bug]: Removal of obsolete members is a breaking change and should cause a semver-major version bump
### Description

Various functions like `HasCount` were removed in https://github.com/thomhurst/TUnit/commit/df31e910e144cd8d91a5218ace0b4f06d7438419

### Expected Behavior

Breaking changes cause a semver-major version bump.

### Actual Behavior

The change was introduced in a minor release, [v1.27.0](https://github.com/thomhurst/TUnit/releases/tag/v1.27.0)

### Steps to Reproduce

1. Have tests that compile with version < 1.27
2. Upgrade
3. Observe compilation errors

### TUnit Version

1.33.0

### .NET Version

NET 10

### Operating System

Linux

### IDE / Test Runner

dotnet CLI (dotnet test / dotnet run)

### Error Output / Stack Trace

```shell

```

### Additional Context

_No response_

### IDE-Specific Issue?

- [ ] I've confirmed this issue occurs when running via `dotnet test` or `dotnet run`, not just in my IDE

### PR DESCRIPTION
**Pull request by thomhurst**
## Summary

- Restores public members that were deleted in #5384 (v1.27.0), reapplying their original `[Obsolete]` attributes so v1.x users can upgrade without compile errors.
- Actual deletion is deferred to the v2 major bump — tracked in #5604.

Fixes #5539.

## Restored members

**TUnit.Assertions**
- `CountWrapper<TCollection, TItem>` and `LengthWrapper` (recreated verbatim under `TUnit.Assertions.Conditions.Wrappers`)
- `CollectionAssertionBase<TCollection, TItem>.HasCount()` / `.HasCount(int)`
- `AssertionExtensions.HasLength(IAssertionSource<string>)` / `.HasLength(IAssertionSource<string>, int)`

**TUnit.Core**
- `TestBuilderContext.ObjectBag` and `TestRegisteredContext.ObjectBag` (alias `=> StateBag`)
- `Timing` record
- `ITestOutput.Timings` property + `ITestOutput.RecordTiming(Timing)` method, bridged in `TestContext.Output.cs` to the internal `TimingEntry` storage. Adds `_timingsLock` to make user-facing concurrent `RecordTiming` calls safe (engine no longer writes to this list — OTel handles timing internally).

PublicAPI snapshots regenerated for net8.0 / net9.0 / net10.0 / net472.

## Test plan
- [x] `dotnet build TUnit.Core` — clean
- [x] `dotnet build TUnit.Assertions` — clean
- [x] `dotnet build TUnit.Engine` — clean
- [x] `TUnit.PublicAPI` tests pass on net8.0, net9.0, net10.0, net472
- [ ] CI green

### CODE REVIEW

**Comment by thomhurst** [comment]
Thanks for the review! Pushed b11614354 addressing all three:

1. **CountWrapper duplication** — extracted `GetCount` + `MapToCount` helpers, removed ~100 lines of copy-paste.
2. **Stale `Timings` comment** — clarified: engine writes are sequential per-test (lifecycle-ordered), `_timingsLock` only guards the obsolete user-facing `ITestOutput.RecordTiming` bridge.
3. **`LengthWrapper` API surface** — verified against `df31e91^`: original only had `EqualTo`. Restored verbatim, no `GreaterThan` etc. ever existed on it. Users wanting full numeric API have always needed `Length()` (the new one). No additional restoration needed.
