### ISSUE TITLE
Missing polyfill for ModuleInitializerAttribute in v0.50.0

### ISSUE THREAD

**Issue by PhilippNaused** [thomhurst/TUnit#2734]
`ModuleInitializerAttribute` used to have a polyfill generator before 0.50 to allow TUnit to run in .NET Framework.
That seems to be missing in 0.50. My TUnit tests are all multitargeting .NET Core and .NET Framework and the framework one all fail to compile with 0.50 with this error:
`error CS0122: 'ModuleInitializerAttribute' is inaccessible due to its protection level`

Was this polyfill removed intentionally? If so, what do I have to do to make .NET Framework tests compile again?

**Comment by thomhurst** [comment]
It should be bringing in the Polyfill package for net standard. I'll take a look.

In the meantime,.try.installing the "Polyfill" package for net framework. It brings a bunch of newer features to older runtimes.

**Comment by PhilippNaused** [comment]
@thomhurst I've seen #2745 and I don't think that will fix it.

Firstly, `'$(TargetFramework)' == 'netstandard2.0'` doesn't work since `TargetFramework` is the tfm of my test assembly, which is `net48`.
You would need to use something like `!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))` to ensure it's added to any project that doesn't have .NET 6 or later as a target.

Hard-coding a version may be a problem if the user already uses Polyfill.\
It could also break the build if your are using central package management with version overrides disabled. You could set `IsImplicitlyDefined='true'` to fix that.

**Comment by thomhurst** [comment]
Does this still happen on the latest version too?

**Comment by PhilippNaused** [comment]
I tested `0.52.49`, but I'm using central package management.

Unfortunately, the condition `!Exists('$(NuGetPackageRoot)polyfill')` doesn't work.
`NuGetPackageRoot` doesn't always have a trailing slash. And just because the package exists in the cache doesn't mean that is is used in the current repository.

**Comment by PhilippNaused** [comment]
I tried adding a trailing slash to the path and now the projects cannot be loaded in VS anymore with this error:
`A NuGet restore loop has been detected in project '<Path>'. Further restores have been aborted. The project might be in a bad state.`
That only happens in VS. If I build via dotnet cli, it simply doesn't add the package reference.
