### ISSUE TITLE
Mixing `MethodDataSourceAttribute` returning `IEnumerable<Func<T>>` and `TimeoutAttribute` causes a compilation failure 

### ISSUE THREAD

**Issue by afscrome** [thomhurst/TUnit#1299]
Hope you're doing well.  Using TUnit for the first time, and I'm getting compilation errors when I try to mix a `MethodDataSource` returning `IEnumerable<Func<T>>`  with a `Timeout` attribute.  Both compile fine individually, but fail when used together

```cs
    public static IEnumerable<Func<int>> FuncDataSource()
    {
        yield return () => 1;
        yield return () => 2;
    }

    // Argument 1: cannot convert from 'System.Func<int>' to 'int'
    [MethodDataSource(nameof(FuncDataSource))]
    [Timeout(5_000)]
    [Test]
    public async Task FuncDataSourceTest(int value, CancellationToken cancellationToken)
    {
        await Assert.That(value).IsEqualTo(1);
    }
```

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS1503	Argument 1: cannot convert from 'System.Func<int>' to 'int'	_.Tests	REDCACTED\artifacts\obj\REDCACTED.Tests\debug\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\CredentialRetrieverTests_Tests_REDCACTED_Tests_181384e1cbf64ac492c815e2ee92485f.Generated.cs	55		
```

If I return `IEnumerable<T>` instead of `IEnumerable<Func<T>>` in my data source, then the code compiles

```cs
    public IEnumerable<int> DataSource()
    {
        yield return 1;
        yield return 2;
    }

    [MethodDataSource(nameof(DataSource))]
    [Timeout(5_000)]
    [Test]
    public async Task DataSourceTest(int value, CancellationToken cancellationToken)
    {
        await Assert.That(value).IsEqualTo(1);
    }
```

Equally if my datasource returns `IEnumerable<Func<T>>` without using `Timeout`, it also compiles

```cs
    public IEnumerable<Func<int>> FuncDataSource()
    {
        yield return () => 1;
        yield return () => 2;
    }

    [MethodDataSource(nameof(FuncDataSource))]
    [Test]
    public async Task FuncDataSourceTest(int value)
    {
        await Assert.That(value).IsEqualTo(1);
    }
```

**Comment by thomhurst** [comment]
Hey Alex. Hope you're good. Will get a fix out shortly.

**Comment by thomhurst** [comment]
Should be fixed in v0.4.10
